### ISSUE TITLE
class tour not found in view

### ISSUE THREAD

**Issue by arjenmeijer** [MyCademy/yii2-bootstrap-tour#2]
<?php
// https://github.com/MyCademy/yii2-bootstrap-tour
Tour::widget([
    'clientOptions' => [ //Bootstrap Tour Options, see: http://bootstraptour.com/api/
        'steps' => [
            [
                'element' => "#meters ...

Do I have to add a namespace?

**Comment by rhertogh** [comment]
Yes, you're right. I see it's missing from the example:
`use MyCademy\BootstrapTour\Tour`

**Comment by arjenmeijer** [comment]
add a semicolon after Tour to make it perfect.

**Comment by rhertogh** [comment]
Jep, thx!
