### ISSUE TITLE
Tour::widget([ needs a echo? + how to debug?

### ISSUE THREAD

**Issue by arjenmeijer** [MyCademy/yii2-bootstrap-tour#3]
Tour::widget([    needs an echo?

But even with an echo, noting is shown.

Any advise what is the easiest way to debug if tour is not working?

**Comment by rhertogh** [comment]
Hi Arjen,

Do you got everything running so var (including the other issues 1 through 5)?

**Comment by arjenmeijer** [comment]
Yes! It is working fine, but I have to fine tune the settings of the plugin a little bit further. Your part is working oke.

**Comment by rhertogh** [comment]
Ok, good to hear. Then I'll close the issues.
